### ISSUE TITLE
Scroll to bottom doesn't work properly with MathJax elements?

### ISSUE THREAD

**Issue by sabetAI** [asnunes/mathjax3-react#8]
I'm trying to render `MathJax` elements in a list, and scroll to the bottom after this render is complete. I'm unable to achieve this behaviour, even with hooks like `useLayoutEffect`. Here is a sandbox producing the issue: [https://codesandbox.io/s/romantic-cache-ifj9f?file=/src/App.js](https://codesandbox.io/s/romantic-cache-ifj9f?file=/src/App.js)

Any suggestions of ways to fix this?

**Comment by asnunes** [comment]
Hi, @sabetAI. Your example is actually implemented using [react-mathjax3](https://github.com/ggunti/react-mathjax3#readme) as a dependency, not `mathjax3-react`, this repository. The first one uses version 2.7.1 of MathJax, not v3. These APIs are very different from each other. You may publish an example using `mathjax3-react` and I will be glad to help or you may post an issue on `react-mathjax3` repository where they can help you better if it is the case. 

Closing it by now.
